<a href="https://colab.research.google.com/github/randerson2113/CSC7002PythonCourse/blob/main/Week_3_Exercises_Anderson_Robert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSC 7002 - Python Programming
## Week 3 Exercises - Robert M Anderson

> Complete exercises 7.1 - 7.23


In [ ]:
# import NumPy for all exercises
import numpy as np

##**7.1** - (Filling arrays)
Fill a 2-by-3  with ones, a 3-by-3  with zeros and a 2-by-5 array with 7s.

In [ ]:
# create a 2x3 array with ones
ones = np.ones([2,3])

# create a 3x3 array zeroes
zeros = np.zeros([3,3])

# create a 2x5 array with sevens
sevens = np.full([2,5], 7)

# prove desired output
print(ones)
print(zeros)
print(sevens)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


##**7.2**(Broadcasting)
Use arrange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:

>a. Cube every element of the array

>b. Add 7 to every element of the array

>c. Multiply every element of the array by 2


In [ ]:
# create 2x2 array using arange
array = np.arange(4).reshape(2,2)
print(array)

# exercise 7.2.a - cube array elements
cube = array ** 3
print(cube)

# exercise 7.2.b - add 7 to array elements
add_seven = array + 7
print(add_seven)

# exercise 7.2.c - multiply array elements by 2
muliply_two = array * 2
print(muliply_two)

[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


##**7.3** (Element-Wise  Multiplication)
Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [ ]:
# create first array, print
even_array = np.arange(2,19,2).reshape(3,3)
print(even_array)

# create second array, print
descending_array = np.arange(9,0,-1).reshape(3,3)
print(descending_array)

# print the product of the arrays
print(even_array * descending_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]


##**7.4** (array from List of Lists)
Create a 2-by-5 array from an argument which is a list of the two five-element lists [2,3,5,7,11] and [13,17,19,23,29].


In [ ]:
# create a 2x5 array from given lists
list1 = [2,3,5,7,11]
list2 = [13,17,19,23,29]

array = np.array([list1, list2]).reshape(2,5) # reshape is redundant, but proves fit
print(array)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


##7.5 (Flattening arrays with flatten vs. ravel)
Create a 2-by-3 array containing the first six powers of 2 beginning with 2^0. Flatten the array first with method flatten, then with ravel. In each case, display the result then display the original array to show that it was unmodified.

In [ ]:
# create an array of twos
array = np.full([2,3],2)
print(array)

# transform array contents with math
for i in range(2):
  for j in range(3):
    array[i][j] = 2**(i*3+j)

# why this works:
# i * 3 + j = [0] * 3 + [0] = 1
# i * 3 + j = [0] * 3 + [1] = 1
# i * 3 + j = [0] * 3 + [2] = 2
# i * 3 + j = [1] * 3 + [0] = 3
# i * 3 + j = [1] * 3 + [1] = 4
# i * 3 + j = [1] * 3 + [2] = 5

print(array)
print(array.flatten())
print(array.ravel())
print(array)

[[2 2 2]
 [2 2 2]]
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]


##7.6 (Research: array Method astype)
Research in the NumPy documentation the array method astype, which converts an array’s elements to another type. Use linspace and reshape to create a 2-by-3  with the values 1.1, 2.2, ..., 6.6. Then use astype to convert the array to an array of integers.

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

# create an evenly spaced 2x3 array from 1.1 to 6.6
array = np.linspace(1.1,6.6,6).reshape(2,3)
print(array)

# cast as integer
array = array.astype(int)
print(array)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


##7.7 (Challenge Project: Reimplement NumPy array Output)
You saw that NumPy outputs two-dimensional arrays in a nice column-based format that right-aligns every element in a field width. The field width’s size is determined by the array element value that requires the most character positions to display. To understand how powerful it is to have this formatting simply built-in, write a function that reimplements NumPy’s array formatting for two-dimensional arrays using loops. Assume the array contains only positive integer values.

In [ ]:
new_array = np.arange(0,100000,5000).reshape(4,5)
print(new_array)

# set max parameters
max_val = new_array[-1,-1] # make the width as wide as the last element
max_width = len(str(max_val)) # width of the string, not the int

# loop through array and print each row, column value
for i in range(4):
  for j in range(5):
    print(f"{new_array[i][j]:>{max_width}}", end=" ") # Use max_width for right-alignment
  print()

[[    0  5000 10000 15000 20000]
 [25000 30000 35000 40000 45000]
 [50000 55000 60000 65000 70000]
 [75000 80000 85000 90000 95000]]
    0  5000 10000 15000 20000 
25000 30000 35000 40000 45000 
50000 55000 60000 65000 70000 
75000 80000 85000 90000 95000 


##7.8 (Challenge Project: Reimplement DataFrame Output)
You saw that pandas displays arrays in an attractive column-based format with row and column labels. The values within each column are right aligned in the same field width, which is determined by that column’s widest value. To understand how powerful it is to have this formatting built-in, write a function that reimplements DataFrame formatting using loops. Assume the DataFrame contains only positive integer values and that both the row and column labels are each integer values beginning at 0.

## 7.9 (Indexing and Slicing arrays)
Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:
              
                
> a. Select row 2.

> b. Select column 5.
                
> c. Select rows 0 and 1.
                
> d. Select columns 2–4.
                
> e. Select the element that is in row 1 and column 4.
                
> f. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

In [ ]:
#([R:R],[C:C]) -  :, "ignores" R condition, blank ignores C
array = np.arange(1,16).reshape(3,5)
print(array)

# a - select row 2
print("a - select Row 2")
print(array[1])

# b - select column 5
print("b - select Column 5")
print(array[:,4])

# c - select rows 0 and 1
print("c - select Rows 0 and 1")
print(array[0:2])

# d - select columns 2-4
print("d - select Columns 2-4")
print(array[:,2:5])

# e - select element in row 1 column 4
print("e - select Element in Row 1 Column 4")
print(array[1,4]) # confusing terminoligy - could be [0,4] if we mean first row

# f - select all elements from row 1 and 2 in columns 0,2,4
print("f - select All Elements from Rows 1 and 2 in Columns 0,2,4")
print(array[1:3, [0,2,4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
a - select Row 2
[ 6  7  8  9 10]
b - select Column 5
[ 5 10 15]
c - select Rows 0 and 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
d - select Columns 2-4
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
e - select Element in Row 1 Column 4
10
f - select All Elements from Rows 1 and 2 in Columns 0,2,4
[[ 6  8 10]
 [11 13 15]]


## 7.10 (Project: Two-Player, Two-Dimensional Tic-Tac-Toe)
Write a script to play two-dimensional Tic-Tac-Toe between two human players who alternate entering their moves on the same computer. Use a 3-by-3 two-dimensional array. Each player indicates their moves by entering a pair of numbers representing the row and column indices of the square in which they want to place their mark, either an 'X' or an 'O'. When the first player moves, place an 'X' in the specified square. When the second player moves, place an 'O' in the specified square. Each move must be to an empty square. After each move, determine whether the game has been won and whether it’s a draw.

##7.11 (Challenge Project: Tic-Tac-Toe with Player Against the Computer)
Modify your script from the previous exercise so that the computer makes the moves for one of the players. Also, allow the player to specify whether he or she wants to go first or second.

##7.12 (Super Challenge Project: 3D Tic-Tac-Toe with Player Against the Computer)

Develop a script that plays three-dimensional Tic-Tac-Toe on a 4-by-4-by-4 board.
> [Note: This is an extremely challenging project! In the “Deep Learning” chapter, you’ll learn techniques that will help you develop and AI-based approach to solving this problem.]

## 7.13 (Research and Use Other Broadcasting Capabilities)
Research the NumPy broadcasting rules, then create your own arrays to test the rules.

In [ ]:
# numpy broadcasting rules
# https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting
import numpy as np

# create arbitrary arrays
array = (0)
array1 = np.array([1,2,3])
array2 = np.array([[1,2],[3,4],[5,6]])
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# broadcast functions
try:
  print(array + array1)
except Exception as e:
  print(e)

try:
  print(array1 + array2)
except Exception as e:
  print(e)

try:
  print(array2 + array3)
except Exception as e:
  print(e)

try:
  print(array2 * array3)
except Exception as e:
  print(e)

try:
  print(array3 + array1)
except Exception as e:
  print(e)

try:
  print(array3 * array) # multiplying by a scalar sets all values to scalar value
except Exception as e:
  print(e)

[1 2 3]
operands could not be broadcast together with shapes (3,) (3,2) 
operands could not be broadcast together with shapes (3,2) (2,2,3) 
operands could not be broadcast together with shapes (3,2) (2,2,3) 
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


## 7.14 (Horizontal and Vertical Stacking)
Create the two-dimensional arrays

```python
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

```

> a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
                
> b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
                
> c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
                
> d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

In [ ]:
# create 2d arrays
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

# a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1, array2))
print("Array 3: \n",array3)
print(np.shape(array3))
# b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.hstack((array1,array2))
print("Array 4: \n",array4)
print(np.shape(array4))
# c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
array5 = np.vstack((array4,array4)).reshape(4,4)
print("Array 5: \n",array5)
print(np.shape(array5))
# d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.hstack((array3,array3)).reshape(4,4)
print("Array 6: \n",array6)
print(np.shape(array6))

Array 3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
Array 4: 
 [[0 1 4 5]
 [2 3 6 7]]
(2, 4)
Array 5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
(4, 4)
Array 6: 
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
(4, 4)


## 7.15 (Research and Use NumPy’s concatenate Function)
Research NumPy function concatenate, then use it to reimplement the previous exercise.

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy-concatenate
# np.concatenate((a, b), axis=0) - axis = 0 is vertical stack, axis = 1 is horizontal stack

# create 2d arrays
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

testoutput = np.ndarray((4,4))

# a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.concatenate((array1, array2), axis = 0)
print("Array 3: \n",array3)
print(np.shape(array3))
# b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.concatenate((array1,array2), axis = 1)
print("Array 4: \n",array4)
print(np.shape(array4))
# c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
array5 = np.concatenate((array4,array4), axis = 0).reshape(4,4)
print("Array 5: \n",array5)
print(np.shape(array5))
# d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.concatenate((array3,array3), axis = 1, out = testoutput).reshape(4,4) # testing the out= argument
print("Array 6: \n",array6)
print(np.shape(array6))

Array 3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
Array 4: 
 [[0 1 4 5]
 [2 3 6 7]]
(2, 4)
Array 5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
(4, 4)
Array 6: 
 [[0. 1. 0. 1.]
 [2. 3. 2. 3.]
 [4. 5. 4. 5.]
 [6. 7. 6. 7.]]
(4, 4)


##7.16 (Research: NumPy tile Function)
Research and use NumPy’s tile function to create a checkerboard pattern of dashes and asterisks.

In [ ]:
# numpy tile function
# https://numpy.org/doc/stable/reference/generated/numpy.tile.html#numpy.tile

array = np.array([['-','*'], ['*', '-']])
print(np.tile(array, (4,4)))


[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]


## 7.17 (Research: NumPy bincount Functions)
Research and use the NumPy bincount function to count the number of occurrences of each non-negative integer in a 5-by-5 array of random integers in the range 0–99.

## 7.18 (Median and Mode of an array)
NumPy arrays offer a mean method, but not median or mode. Write functions median and mode that use existing NumPy capabilities to determine the median (middle) and mode (most frequent) of the values in an array. Your functions should determine the median and mode regardless of the array’s shape. Test your function on three arrays of different shapes.

##7.19 (Enhanced Median and Mode of an array)
Modify your functions from the previous exercise to allow the user to provide an axis keyword argument so the calculations can be performed row-by-row or column-by-column on a two-dimensional array.

#7.20 (Performance Analysis)

In this chapter, we used %timeit to compare the average execution times of generating a list of 6,000,000 random die rolls vs. generating an array of 6,000,000 random die rolls.
Though we saw approximately two orders of magnitude performance improvement with , we generated the list and the array using two different random-number generators and different techniques for building each collection. If you use the same techniques we showed to generate a one-element list and a one-element array, creating the list is slightly faster. Repeat the %timeit operations for one-element collections. Then do it again for 10, 100, 1000, 10,000, 100,000 and 1,000,000 elements and compare the results on your system. The table below shows the results on our system, with measurements in nanoseconds (ns), microseconds (us), milliseconds (ms) and seconds (s).

> Textbook table (variance omitted in most columns)
Number of values|List average exection time|array average execution time
--|--|--
1|1.56us +- 25.2ns|1.89us +- 24.4ns
10|11.6us|1.96us
100|109us|3us
1000|1.09ms|12.3us
10000|11.1ms|102us
100000|111ms|1.2ms
1000000|1.1s|10.1ms

This analysis shows why %timeit is convenient for quick performance studies. However, you also need to develop performance-analysis wisdom. Many factors can affect performance—the underlying hardware, the operating system, the interpreter or compiler you’re using, the other applications running on your computer at the same time, and many more. The way we thought about performance over the years is changing rapidly now with big data, data analytics and artificial intelligence. As we head into the AI portion of the book, you’ll place enormous performance demands on your system, so it’s always good to be thinking about performance issues.

##7.21 (Shallow vs. Deep Copy)
In this chapter, we discussed shallow vs. deep copies of arrays. Python’s built-in list and dictionary types have  methods that perform shallow copies. Using the following dictionary
              
```python
  dictionary = {'Sophia': [97,88]}
```           
                
demonstrate that a dictionary’s  method indeed performs a shallow copy. To do so, call copy to make the shallow copy, modify the list stored in the original dictionary, then display both dictionaries to see that they have the same contents.
                          
 Next, use the  module’s deepcopy function to create a deep copy of the dictionary. Modify the list stored in the original dictionary, then display both dictionaries to prove that each has its own data.

##7.22(Pandas: Series) Perform the following tasks with pandas Series:
              
                
>   a. Create a Series from the list [7,11,13,17].           
                
>   b. Create a Series with five elements that are all .
                
>   c. Create a Series with 20 elements that are all random numbers in the range  0 to 100. Use method describe to produce the Series’ basic descriptive statistics.
                
>   d. Create a Series called temperatures of the floating-point values 98.6, 98.9, 100.2 and 97.9. Using the index keyword argument, specify the custom indices 'Julie', 'Charlie', 'Sam' and 'Andrea'.
                
>   e. Form a dictionary from the names and values in Part (d), then use it to initialize a Series.

##7.23 (Pandas: DataFrames) Perform the following tasks with pandas DataFrames:
              
> a. Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.
              
> b. Recreate the DataFrame temperatures in Part (a) with custom indices using the  keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'.
              
> c. Select from temperatures the column of temperature readings for 'Maxine'.
              
> d. Select from temperatures the row of 'Morning' temperature readings.
              
> e. Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
              
> f. Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'.
              
> g. Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Evening'.
              
> h. Use the describe method to produce temperatures’ descriptive statistics.
              
> i. Transpose temperatures.
              
> j. Sort temperatures so that its column names are in alphabetical order.